[[constraint]]
  name = "k8s.io/cli-runtime"
  version = "kubernetes-1.12.2"

[[override]]
  name = "k8s.io/klog"
  version = "=v0.1.0"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.12.2"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.12.2"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.12.2"

[prune]
  go-tests = true
  unused-packages = true
