apiVersion: v1
kind: Namespace
metadata:
  name: case-3-accessmany-source
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-a
  namespace: case-3-accessmany-source
  labels:
    app: a
spec:
  containers:
    - name: pod-a
      image: nginx:stable
      volumeMounts:
        - mountPath: /source
          name: vol-a
          readOnly: true
  volumes:
    - name: vol-a
      persistentVolumeClaim:
        claimName: pvc-a
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-a
  namespace: case-3-accessmany-source
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1G
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-b
  namespace: case-3-accessmany-source
  labels:
    app: b
spec:
  containers:
    - name: pod-b
      image: nginx:stable
      volumeMounts:
        - mountPath: /target
          name: vol-b
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - topologyKey: kubernetes.io/hostname
          labelSelector:
            matchLabels:
              app: a
  volumes:
    - name: vol-b
      persistentVolumeClaim:
        claimName: pvc-b
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-b
  namespace: case-3-accessmany-source
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
