apiVersion: v1
kind: Namespace
metadata:
  name: test-same-ns
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-a
  namespace: test-same-ns
  labels:
    app: a
spec:
  containers:
    - name: pod-a
      image: nginx:stable
      volumeMounts:
        - mountPath: /source
          name: vol-a
  volumes:
    - name: vol-a
      persistentVolumeClaim:
        claimName: pvc-a
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-a
  namespace: test-same-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-b
  namespace: test-same-ns
  labels:
    app: b
spec:
  containers:
    - name: pod-b
      image: nginx:stable
      volumeMounts:
        - mountPath: /target
          name: vol-b
  volumes:
    - name: vol-b
      persistentVolumeClaim:
        claimName: pvc-b
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-b
  namespace: test-same-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
