---
# Used ahmetb/kubectx as reference: https://github.com/ahmetb/kubectx
name: Continuous Integration
on:  # yamllint disable-line rule:truthy
  push:
  pull_request:
jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Go
        uses: actions/setup-go@v1.1.3
        with:
          go-version: 1.16
      - name: Ensure gofmt
        run: test -z "$(gofmt -s -d .)"
      - name: Ensure go.mod is already tidied
        run: go mod tidy && git diff --no-patch --exit-code
      - name: Run unit tests
        run: go test ./...
      - name: Build with Goreleaser
        uses: goreleaser/goreleaser-action@v2.4.1
        with:
          version: v0.161.1
          args: release --snapshot --skip-publish --rm-dist
