---
# Used ahmetb/kubectx as reference: https://github.com/ahmetb/kubectx
name: Release
on:  # yamllint disable-line rule:truthy
  push:
    tags:
      - 'v*.*.*'
jobs:
  goreleaser:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Go
        uses: actions/setup-go@v1.1.3
        with:
          go-version: 1.16
      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v2.4.1
        with:
          version: v0.161.1
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
